### ISSUE TITLE
Empty .dot for smg model

### ISSUE THREAD

**Issue by Miracle-qi** [prismmodelchecker/prism-games#15]
I can successfully export the strategy `.dot` for csg model. When I export the strategy for smg model, the generated `.dot` is empty even for the provided examples. It is weird.  The used prism-game is the latest 3.1 version. I will appreciate it if you can provide any advice or possible solution to solve this issue.

**Comment by davexparker** [comment]
The solution is discussed here: https://groups.google.com/g/prismmodelchecker/c/opSFJ3WKZNs
