### ISSUE TITLE
Unable to Set CUDD Max Memory on Windows

### ISSUE THREAD

**Issue by ribsthakkar** [prismmodelchecker/prism-games#7]
I am trying to increase the max memory for CUDD on Prism Games GUI on windows by updating the batch script, but it interprets the command line arguments as a file rather than configuration arguments.

For example, I changed the last line of the batch script as follows:
`start "PRISM"  javaw -Xmx16g -Xss1g -Djava.library.path="%PRISM_DIR%\lib" -classpath "%CP%" userinterface/GUIPrism %* -cuddmaxmem 8g`
However, when running the script it says "cannot open file -cuddmaxmem" 
Furthermore, when I tried running through the command line and passing in a file argument and then the cudd memory limits as follows:
`.\xprism.bat '..\..\..\Users\Rishabh Thakkar\Documents\two_player_smg.pm' -cuddmaxmem 8g`
I don't see invalid file, but I just see that CUDD memory limit has not changed.

**Comment by davexparker** [comment]
Hi @ribsthakkar. We don't currently allow `-cuddmaxmem` to be pass to the GUI (PRISM or PRISM-games), only from the command-line. However, if you are verifying stochastic games, this is currently a purely explicit-state implementation, so it will be unaffected by CUDD memory. Java memory limits will have more impact. What kind of memory issues are you having?

**Comment by ribsthakkar** [comment]
Ahhh I see. 

Regarding memory issues, it is simply that model implementation is somewhat naive. I am exceeding upwards of 48 GB RAM and 30 GB of swap memory haha before my machine gives out. I have upped the Java Heap space to simply 128GB, but I just think I am breaching OS limits on swap and the performance limits of Java's garbage collector at that point since the program just hangs as soon as it seems like I reach a total of about 75 GB RAM+swap.
