### ISSUE TITLE
Question: Support for Dynamic Update Probabilities

### ISSUE THREAD

**Issue by ttowncompiled** [prismmodelchecker/prism-games#9]
Hello everyone! I've been using SMGs in my research. I'm currently looking at PRISM games, but it's not readily obvious to me whether or not PRISM supports SMGs with dynamic transition (update) probabilities.

I'm currently working on a project where a drone is tasked with locating an intel cache within a large grid. Both the drone and the intel cache are mobile. Each turn, they can move to one of their 8 cardinally or ordinally adjacent squares. Neither the drone nor the intel cache may leave the grid. I have devised a set of strategies that the drone can use to attempt to locate the intel cache. I am using multiple SMGs to evaluate the expected likelihood that the drone locates the intel cache given each pre-defined strategy.

The description of the problem requires that the drone has a set of probabilities associated with its 8 possible moves. However, the probability associated with each particular move must change each turn. Does PRISM-games support this kind of SMG construction?

**Comment by ttowncompiled** [comment]
I should also ask if PRISM-games can support blocking behavior where a condition in the guard is false for a random number of turns before becoming true? This is used in some of our applications to simulate actions that have an associated 'cooldown'.

**Comment by davexparker** [comment]
Hi @ttowncompiled. The probability can depend on the current state. Either make the probability in the command an expression in terms of state variables, or use multiple commands with different guards for the different cases. So if the probability "must change each turn", then the current turn needs to be available as a state variable. Does that help?

**Comment by davexparker** [comment]
For the second question, it again needs to in the state. If you have a state variable counting the turns, you are free to use that to make the behaviour different after some number of turns.

**Comment by ttowncompiled** [comment]
Thanks @davexparker ! That certainly addresses my second question. As for "[making] the probability in the command an expression in terms of state variables," I'm concerned that this won't be feasible for my application. I have a 16x16 grid, where each cell can have a distinct probability of being moved to. The probability of each cell is quite complex to compute, so I have to use a 16x16 matrix to maintain the probabilities for each location. The probability of each cell is updated at the end of each round.

The purpose of the probability matrix is to determine the likelihood that the intel cache (which is hiding) is at any given location within the 16x16 grid. The drone (which is seeking the intel cache) is greedy, so it will always move to the adjacent square that has the greatest likelihood of containing the intel cache. I therefore have to guard the drone's available moves so that it can only select the adjacent square that has the greatest likelihood as determined by the probability matrix.

**Comment by davexparker** [comment]
Thanks for clarifying @ttowncompiled. For the kind of situation you mention, it is not uncommon to go down the route of generating PRISM models via a script of some sort. There is also the option of building models programmatically (in Java) via our ModelGenerator interface.

I'll mark this as "closed" for now, but please feel free to ask further questions, either here, or on our user's forum: https://groups.google.com/g/prismmodelchecker

**Comment by ttowncompiled** [comment]
I hadn't considered either of these. Thank you so much @davexparker. I'll definitely look into both of these options. It sounds like the ModelGenerator interface may be what I need.
